### ISSUE TITLE
Deleting a children from a choral makes the choral unaccessable

### ISSUE THREAD

**Issue by ecuellog** [ChoralCloud/ChoralWeb#112]
If you created a choral "CHORAL1" that has say "CHILDREN1" and you delete this children, when trying to view the chart for CHORAL1 you will get "TypeError: Cannot read property 'choralId' of null"

**Comment by andreirtaylor** [comment]
Can you give me sample chorals so that I can test this?

**Comment by james-woo** [comment]
Deleting the child choral does not get removed in parent choral children element. We might have to iterate over all the chorals to see which chorals have the deleted child as a child?

**Comment by james-woo** [comment]
Have an easy fix, will be making a pr soon

**Comment by cpjk** [comment]
Unable to replicate on master
