### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by andreirtaylor** [ChoralCloud/ChoralWeb#21]
We need to start thinking about logging

- What we want to log
- How we are going to log it.

**Comment by cpjk** [comment]
I think:

When any service sends a message. 
When any service receives a message.

If possible we should log to a central place. There should be a single place you can go for all logs. Separated into sub directories of course.

**Comment by andreirtaylor** [comment]
What are the options for a central logging? Would [papertrail](https://papertrailapp.com/plans) or [log entries](https://logentries.com/pricing/) be appropriate or should we try to host our own?
