### ISSUE TITLE
List children on choral view page

### ISSUE THREAD

**Issue by andreirtaylor** [ChoralCloud/ChoralWeb#34]

**Comment by cpjk** [comment]
How about we just show a list of the direct children, and  have a "show" page for each choral, e.g. /chorals/<choralId> and there we have all the detailed info about the choral, including actual links to the direct children. (we might not have room on /chorals for even all the direct children

**Comment by cpjk** [comment]
I think showing more than direct children of a choral right now is a stretch goal. It would be nice to have some sort of tree showing the topology tho.

**Comment by cpjk** [comment]
maybe someone can work on that later, but now i think we focus on getting the main features in, not necessarily looking amazing

**Comment by andreirtaylor** [comment]
This works for me. I was just thinking that we should be able to see the direct children in the web view.

**Comment by andreirtaylor** [comment]
And by this I mean treating this as a stretch goal

**Comment by cpjk** [comment]
cool.

**Comment by andreirtaylor** [comment]
This is definitely not necessary anymore
