### ISSUE TITLE
Update navigation

### ISSUE THREAD

**Issue by james-woo** [ChoralCloud/ChoralWeb#48]
Right now we have two pages:
Dashboard
Chorals

Perhaps we could add these pages:
**Home** 
- Their current chorals
- Their account information
- Stats about their chorals, like how many requests/sec they are using
- Their api keys, secrets (if any)

**Events** #20
**Dashboard** #44
**Chorals** #33 (Add devices to sidebar) and #34 (List children)

**Comment by andreirtaylor** [comment]
I dont think we will have time to implement any account information unfortunately.

But you are right we do need to add in links on the sidebar for 

Devices -> /device/new
New Choral -> /chorals/new
