### ISSUE TITLE
Clean up choral list page

### ISSUE THREAD

**Issue by jboretsky** [ChoralCloud/ChoralWeb#71]
I think we could make this page nicer. Instead of being a table, we could maybe use cards with buttons on them (the same buttons as we currently have on the table entries). 

Also I don't think we should show the function on the table rows (or cards if we do that), we won't ever have enough space to show the whole thing, so we should probably just remove it, and instead add a button to view/edit the function where something like a modal would pop up, or just another page for now.

**Comment by jboretsky** [comment]
Actually, we might wanna think about how we're going to do this a little more. I think having 3 different pages  showing kind of the same things (devices, chorals, and home) is confusing for users. I think that home should just be where everything is, they should all be cards, and we should have a dropdown or something where we just filter the chorals differently. If we are already doing this for the different routes, it should be pretty straightforward to do this. I think this would be a lot cleaner.

**Comment by james-woo** [comment]
![image](https://user-images.githubusercontent.com/8840965/28534195-a8316f68-7054-11e7-8cbe-fe6bf9f023da.png)
What do you think of this

**Comment by andreirtaylor** [comment]
This is a big simplification. The only thing that sucks is that the menu is only going to have logout in it. I guess we could drop the menu entirely but that also feels weird. I guess we can see how it feels with the new look and deal with the menu then.

**Comment by andreirtaylor** [comment]
In a round about way I'm saying I like this but I don't know what to do with the menu

**Comment by andreirtaylor** [comment]
In a round about way I'm saying I like this but I don't know what to do with the menu
