### ISSUE TITLE
Prevent adding a choral as a child of itself

### ISSUE THREAD

**Issue by cpjk** [ChoralCloud/ChoralWeb#98]

**Comment by andreirtaylor** [comment]
How deep should we go with this should we look at the whole tree or just direct descendants? I can add in a check to line to make this happen on the front end but it wouldnt stop people from doing 


```
         A
          |
         B
          |
         A
```

**Comment by andreirtaylor** [comment]
Actually I dont even know if I think that what I just described is an issue. I mean it doesn't make any sense, but it shouldnt be a problem given the way that we have implemented this.

**Comment by andreirtaylor** [comment]
I think we should just prevent direct children with the parent. Ill add a validator.
